### ISSUE TITLE
Crash in reply

### ISSUE THREAD

**Issue by bdrewery** [bdrewery/PyBorg#11]
<pre>
Error: couldn't connect..Try again later http://tinyurl.com/68xb8xq
lool
Traceback (most recent call last):
  File "../lib/pyborg/pyborg-irc.py", line 594, in <module>
    bot.our_start()
  File "../lib/pyborg/pyborg-irc.py", line 159, in our_start
    self.start()
  File "/export/home/cutie578/PyBorg/lib/pyborg/ircbot.py", line 251, in start
    SimpleIRCClient.start(self)
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 1114, in start
    self.ircobj.process_forever()
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 229, in process_forever
    self.process_once(timeout)
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 214, in process_once
    self.process_data(i)
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 183, in process_data
    c.process_data()
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 581, in process_data
    self._handle_event(Event(command, prefix, target, [m]))
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 604, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 325, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/export/home/cutie578/PyBorg/lib/pyborg/irclib.py", line 1049, in _dispatcher
    getattr(self, m)(c, e)
  File "../lib/pyborg/pyborg-irc.py", line 227, in on_pubmsg
    self.on_msg(c, e)
  File "../lib/pyborg/pyborg-irc.py", line 333, in on_msg
    self.pyborg.process_msg(self, body, replyrate, learn, (body, source, target, c, e), owner=1)
  File "/export/home/cutie578/PyBorg/lib/pyborg/pyborg.py", line 372, in process_msg
    message = self.reply( body )
  File "/export/home/cutie578/PyBorg/lib/pyborg/pyborg.py", line 998, in reply
    sentence[x + 1] = ""
IndexError: list assignment index out of range
</pre>

**Comment by bdrewery** [comment]
Likely due to 7e6dcb1c411fe61622136fefe8e7bd9cdf55018d
