### ISSUE TITLE
Install pyborg

### ISSUE THREAD

**Issue by Anonchan** [bdrewery/PyBorg#34]
I've tried easy_install pip install pip3 install and pyborg.irc install. With very limited success. currently it is looking for pyborg.toml file that is not created nor supplied.

root@USERNAME:/home/USER/pyborg-1up/pyborg# pyborg version
I am a version 1.4.0b1 pyborg!
I'm running on CPython 2.7.12/Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
root@USERNAME:/home/USER/pyborg-1up/pyborg# pyborg irc
Traceback (most recent call last):
  File "/usr/local/bin/pyborg", line 9, in <module>
    load_entry_point('pyborg==1.4.0b1', 'console_scripts', 'pyborg')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyborg-1.4.0b1-py2.7.egg/EGG-INFO/scripts/pyborg_experimental.py", line 258, in irc

  File "build/bdist.linux-x86_64/egg/pyborg/mod/mod_irc.py", line 48, in __init__
  File "build/bdist.linux-x86_64/egg/pyborg/pyborg.py", line 279, in __init__
  File "build/bdist.linux-x86_64/egg/pyborg/pyborg.py", line 254, in load_settings
  File "build/bdist.linux-x86_64/egg/toml.py", line 39, in load
IOError: [Errno 2] No such file or directory: '/root/.config/pyborg/pyborg.toml'

sudo find / -name "pyborg.toml" 2>&1 | grep -v Permission
results in no files on the system names pyborg.toml

**Comment by Anonchan** [comment]
Also from this git repo:

root@io:/home/lionheart/pyborg-1up/pyborg# python3 pyborg-irc.py
  File "pyborg-irc.py", line 29
    print "ERROR !!!!\nircbot.py and irclib.py not found, please install them\n( http://python-irclib.sourceforge.net/ )"
                                                                                                                        ^
SyntaxError: invalid syntax

**Comment by GLolol** [comment]
Pyborg requires Python 2, it's not compatible with Python 3.

**Comment by GLolol** [comment]
You shouldn't be running an IRC bot as root; have you tried running it from a regular user?

**Comment by diveyez** [comment]
ROTFL @ ANON HAHAHAHAH! Thats some funny shit.
